# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='submit_day',
            field=models.TimeField(verbose_name='fecha'),
        ),
    ]
