# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180613_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status_es',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status_fr',
        ),
    ]
