# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180613_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='destacado'),
        ),
    ]
