# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 18:22
from __future__ import unicode_literals

import blogosphere.mixins.models.image
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180521_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', help_text='Usado para ilustración.', max_length=255, upload_to=blogosphere.mixins.models.image.image_upload_to_dispatcher, verbose_name='imagen principal', width_field='width'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='Blog', to='blogs.Author', verbose_name='autores'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', help_text='Usado para ilustración.', max_length=255, upload_to=blogosphere.mixins.models.image.image_upload_to_dispatcher, verbose_name='imagen principal', width_field='width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', help_text='Usado para ilustración.', max_length=255, upload_to=blogosphere.mixins.models.image.image_upload_to_dispatcher, verbose_name='imagen principal', width_field='width'),
        ),
    ]
