# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180524_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ManyToManyField(related_name='Blog', to='blogs.Author', verbose_name='autores'),
        ),
    ]
