# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180524_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='authors',
        ),
    ]
