# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-28 17:52
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20180524_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='tags'),
        ),
    ]
