# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-28 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Usado para construir la URL de la etiqueta.', max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name_plural': 'Etiquetas',
                'verbose_name': 'Etiqueta',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blogs.Tag', verbose_name='etiquetas'),
        ),
    ]
