# region Status Flags
DRAFT = 0
PUBLISHED = 1
HIDDEN = 2

# endregion

# region Permissions Flags
CAN_EDIT_BLOG = 0
CAN_EDIT_POST = 1

CAN_CHANGE_STATUS_BLOG = 2
CAN_CHANGE_STATUS_POST = 3
CAN_CHANGE_STATUS_COMMENT = 4

CAN_DELETE_BLOG = 5
CAN_DELETE_POST = 6
CAN_DELETE_COMMENT = 7

CAN_REFERENCE_POST = 8

# endregion
