"""
Django settings for blogosphere_project project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.contrib import admin

SITE_DOMAIN = 'http://10.10.3.150:8000'

admin.site.site_header = 'Administración de la Blogosfera'
admin.site.site_title = 'Blogosfera'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_PROJECT_DIR = os.path.split(BASE_DIR)[0]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'secret key'

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 'django.contrib.sites',

    # third party apps
    'adminsortable',
    'versatileimagefield',
    'ckeditor',
    'ckeditor_uploader',
    'mptt',

    # custom apps
    'blogosphere.blogs',
]

# COMMENTS_APP = 'django_comments_xtd'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

CSRF_COOKIE_HTTPONLY = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_PROJECT_DIR, 'blogosphere/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.static',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Cuba'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_PROJECT_DIR, 'static_root')

STATICFILES_DIRS = [
    os.path.join(BASE_PROJECT_DIR, 'blogosphere/static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_PROJECT_DIR, 'media')

UPLOAD_TO = 'uploads/'

# Default user model

AUTH_USER_MODEL = 'auth.User'

# region Ckeditor configuration
CKEDITOR_UPLOAD_PATH = os.path.join(UPLOAD_TO, 'ckeditor/')

CKEDITOR_CONFIGS = {
    'default': {

        'toolbar': 'Default',  # put selected toolbar config here
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}

# endregion

# region modeltranslation

gettext = lambda s: s
LANGUAGES = [
    ('es', gettext('ES')),
    ('en', gettext('EN')),
    ('fr', gettext('FR')),

]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'es'

MODELTRANSLATION_LANGUAGES = ('es', 'en', 'fr')
MODELTRANSLATION_FALLBACK_LANGUAGES = ('es', 'en', 'fr')

# MODELTRANSLATION_FALLBACK_LANGUAGES = {'default': ('es', 'en'), 'fr': ('es',)}

MODELTRANSLATION_TRANSLATION_FILES = (
    'blogosphere.blogs.translation',
)

# endregion
